version: '3.9'

services:
    redis:
        image: redis
        command: redis-server
        ports:
            - "6379:6379"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - ENVIRONMENT=development
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
    db:
        image: 'postgres:latest'
        expose:
            - "5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data: